<?php

Route::group(['middleware' => 'auth:api', 'prefix' => 'workflow', 'namespace' => 'App\\Modules\Workflow\Http\Controllers'], function () {
    Route::get('getProcessApplicableChecklistTypes', 'WorkflowController@getProcessApplicableChecklistTypes');
    Route::get('getProcessApplicableChecklistItems', 'WorkflowController@getProcessApplicableChecklistItems');
});

Route::group(['middleware' => 'web', 'prefix' => 'workflow', 'namespace' => 'App\\Modules\Workflow\Http\Controllers'], function () {
    Route::get('/', 'WorkflowController@index');
    Route::post('saveWorkflowCommonData', 'WorkflowController@saveWorkflowCommonData');
    Route::get('getWorkflowParamFromModel', 'WorkflowController@getWorkflowParamFromModel');
    Route::get('getTfdaSystemProcesses', 'WorkflowController@getTfdaSystemProcesses');
    Route::post('softDeleteWorkflowRecord', 'WorkflowController@softDeleteWorkflowRecord');
    Route::post('undoWorkflowSoftDeletes', 'WorkflowController@undoWorkflowSoftDeletes');
    Route::post('deleteWorkflowRecord', 'WorkflowController@deleteWorkflowRecord');
    Route::get('getWorkflowStages', 'WorkflowController@getWorkflowStages');
    Route::get('getWorkflowActions', 'WorkflowController@getWorkflowActions');
    Route::get('getWorkflowTransitions', 'WorkflowController@getWorkflowTransitions');
    Route::post('saveWorkflowStage', 'WorkflowController@saveWorkflowStage');
    Route::post('saveWorkflowTransition', 'WorkflowController@saveWorkflowTransition');
    Route::get('getMenuWorkflowLinkages', 'WorkflowController@getMenuWorkflowLinkages');
    Route::post('saveMenuWorkflowLinkage', 'WorkflowController@saveMenuWorkflowLinkage');
    Route::post('saveMenuWorkFlowsLinkage', 'WorkflowController@saveMenuWorkFlowsLinkage');
    Route::get('showWorkflowDiagram', 'WorkflowController@showWorkflowDiagram');
    Route::post('deleteMenuWorkflowLinkage', 'WorkflowController@deleteMenuWorkflowLinkage');
    Route::post('deleteMenuWorkFlowsLinkage', 'WorkflowController@deleteMenuWorkFlowsLinkage');
    Route::get('getBasicWorkflowDetails', 'WorkflowController@getBasicWorkflowDetails');
    Route::get('getInitialWorkflowDetails', 'WorkflowController@getInitialWorkflowDetails');
    Route::get('getAllWorkflowDetails', 'WorkflowController@getAllWorkflowDetails');
    Route::get('getApplicationSubmissionDetails', 'WorkflowController@getApplicationSubmissionDetails');
    Route::get('getProcessWorkflowStages', 'WorkflowController@getProcessWorkflowStages');
    Route::get('getMenuWorkFlowsLinkages', 'WorkflowController@getMenuWorkFlowsLinkages');
    Route::get('getStageGroups', 'WorkflowController@getStageGroups');
    Route::get('getSystemSubModules', 'WorkflowController@getSystemSubModules');
    Route::get('getProcessApplicableChecklistCategories', 'WorkflowController@getProcessApplicableChecklistCategories');
    Route::get('getProcessEditableFormFields', 'WorkflowController@getProcessEditableFormFields');
    Route::get('getProcessEditableOtherParts', 'WorkflowController@getProcessEditableOtherParts');
    //Route::get('getProcessApplicableChecklistTypes', 'WorkflowController@getProcessApplicableChecklistTypes');
    //Route::get('getProcessApplicableChecklistItems', 'WorkflowController@getProcessApplicableChecklistItems');
    Route::post('syncProcessApplicableChecklistCategories', 'WorkflowController@syncProcessApplicableChecklistCategories');
    Route::post('syncProcessAmendableParts', 'WorkflowController@syncProcessAmendableParts');
    Route::get('getWorkflowStageResponsibleGroups', 'WorkflowController@getWorkflowStageResponsibleGroups');
    Route::get('getSubmissionWorkflowStages', 'WorkflowController@getSubmissionWorkflowStages');
    Route::get('getSubmissionNextStageDetails', 'WorkflowController@getSubmissionNextStageDetails');
    Route::get('getSubmissionResponsibleUsers', 'WorkflowController@getSubmissionResponsibleUsers');
    Route::get('getWorkflowStagePossibleResponsibleGroups', 'WorkflowController@getWorkflowStagePossibleResponsibleGroups');
    Route::post('syncWorkflowStageResponsibleGroups', 'WorkflowController@syncWorkflowStageResponsibleGroups');
    Route::get('getWorkflowAssociatedMenus', 'WorkflowController@getWorkflowAssociatedMenus');
    Route::post('handleApplicationSubmission', 'WorkflowController@handleApplicationSubmission');
    Route::post('handleManagersApplicationSubmissions', 'WorkflowController@handleManagersApplicationSubmissions');
    Route::post('submitApplication', 'WorkflowController@submitApplication');
    Route::post('submitManagerApplicationsGeneric', 'WorkflowController@submitManagerApplicationsGeneric');
    Route::post('submitApplicationReceiving', 'WorkflowController@submitApplicationReceiving');
    Route::post('updateInTrayReading', 'WorkflowController@updateInTrayReading');
    Route::get('getSubmissionRecommendations', 'WorkflowController@getSubmissionRecommendations');
    Route::get('getApplicationStatuses', 'WorkflowController@getApplicationStatuses');
    Route::get('getApplicationReturnDirectives', 'WorkflowController@getApplicationReturnDirectives');
    Route::get('getApplicationTransitioning', 'WorkflowController@getApplicationTransitioning');
    Route::get('getFormFieldsAuth', 'WorkflowController@getFormFieldsAuth');
    Route::get('getProcessOtherPartsAuth', 'WorkflowController@getProcessOtherPartsAuth');
    Route::get('getAlterationFormFieldsAuth', 'WorkflowController@getAlterationFormFieldsAuth');
    Route::get('getAlterationOtherPartsAuth', 'WorkflowController@getAlterationOtherPartsAuth');
    Route::get('getOnlineApplicationSubmissionDetails', 'WorkflowController@getOnlineApplicationSubmissionDetails');
    Route::get('getApplicationAlterationFormFields', 'WorkflowController@getApplicationAlterationFormFields');
    Route::get('getApplicationAlterationOtherParams', 'WorkflowController@getApplicationAlterationOtherParams');
    Route::get('getApplicationAlterationForms', 'WorkflowController@getApplicationAlterationForms');
    Route::post('receiveOnlineApplicationDetails', 'WorkflowController@receiveOnlineApplicationDetails');
    Route::post('getModulesTableData', 'WorkflowController@getModulesTableData');
    Route::get('getProcessApplicableDocumentTypes', 'WorkflowController@getProcessApplicableDocumentTypes');
    Route::post('syncProcessApplicableDocumentTypes', 'WorkflowController@syncProcessApplicableDocumentTypes');
    Route::get('getPortalApplicationStatuses', 'WorkflowController@getPortalApplicationStatuses');
    Route::get('getWorkflowDetails', 'WorkflowController@getWorkflowDetails');
    Route::get('getWorkflowInterfacedetails', 'WorkflowController@getWorkflowInterfacedetails');
});
